# CLAHE Settings
clip_limit: 1.0
tile_grid_size: 3

# Mask Generation Settings
min_mask_area_default: 2000

# Prompt Generation Settings
prompt_type: "bb"  # Options: "bb", "pt", "both"
sampling_mode: "hr"  # Options: "hr", "yc"

# Object that should be included in the indexed masks along with their values.
# If an object is not listed here, it will be assigned a value of 0 in the indexed masks.
indexed_mapping:
  A: 1
  B: 2
  C: 3
  D: 4

# Paths to data files/folder
data_dir: path/to/data/directory/
colormap_path: path/to/colormap.csv

# Structure of data directories (day/plot/camera/...)
images_dir: images/
output_dir: masks/
annotations_file: seedpoints_on_images.csv
